apiVersion: v1
kind: Secret
metadata:
  name: wproofreader-app-lic
  labels:
    helm.sh/chart: wproofreader-1.4.0
    app.kubernetes.io/name: wproofreader
    app.kubernetes.io/instance: wproofreader-app
    app.kubernetes.io/version: "6.16.0.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  license: "your-license-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: wproofreader-app-cert
  labels:
    helm.sh/chart: wproofreader-1.4.0
    app.kubernetes.io/name: wproofreader
    app.kubernetes.io/instance: wproofreader-app
    app.kubernetes.io/version: "6.16.0.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  cert.pem: "your-base64-encoded-certificate"
  key.pem: "your-base64-encoded-private-key"
