apiVersion: v1
kind: Service
metadata:
  name: wproofreader-app
  labels:
    helm.sh/chart: wproofreader-1.0.0
    app.kubernetes.io/name: wproofreader
    app.kubernetes.io/instance: wproofreader-app
    app.kubernetes.io/version: "5.34.3"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: container-port
      protocol: TCP
  selector:
    app.kubernetes.io/name: wproofreader
    app.kubernetes.io/instance: wproofreader-app
