apiVersion: v1
kind: Service
metadata:
  name: wsc-app-sample-wproofreader
  labels:
    app.kubernetes.io/name: wproofreader
    app.kubernetes.io/instance: wsc-app-sample
    app.kubernetes.io/version: "5.25.0"
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: container-port
      protocol: TCP
  selector:
    app.kubernetes.io/name: wproofreader
    app.kubernetes.io/instance: wsc-app-sample
