apiVersion: v1
kind: ServiceAccount
metadata:
  name: wproofreader-app
  labels:
    helm.sh/chart: wproofreader-1.2.0
    app.kubernetes.io/name: wproofreader
    app.kubernetes.io/instance: wproofreader-app
    app.kubernetes.io/version: "5.39.1.0"
    app.kubernetes.io/managed-by: Helm