apiVersion: v1
kind: ServiceAccount
metadata:
  name: wsc-app-sample-wproofreader
  labels:
    app.kubernetes.io/name: wproofreader
    app.kubernetes.io/instance: wsc-app-sample
    app.kubernetes.io/version: "5.25.0"
