apiVersion: v1
kind: PersistentVolume
metadata:
  name: wproofreader-app-dict
  labels:
    helm.sh/chart: wproofreader-1.0.0
    app.kubernetes.io/name: wproofreader
    app.kubernetes.io/instance: wproofreader-app
    app.kubernetes.io/version: "5.34.3"
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: /var/local/dictionaries
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: wproofreader.domain-name.com/app
              operator: Exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wproofreader-app-dict
  labels:
    helm.sh/chart: wproofreader-1.0.0
    app.kubernetes.io/name: wproofreader
    app.kubernetes.io/instance: wproofreader-app
    app.kubernetes.io/version: "5.34.3"
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
