apiVersion: v1
kind: PersistentVolume
metadata:
  name: wsc-app-sample-wproofreader-dict
  labels:
    app.kubernetes.io/name: wproofreader
    app.kubernetes.io/instance: wsc-app-sample
    app.kubernetes.io/version: "5.25.0"
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: /var/local/dictionaries
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: proofreader.company-domain.com/app
              operator: Exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wsc-app-sample-wproofreader-dict
  labels:
    app.kubernetes.io/name: wproofreader
    app.kubernetes.io/instance: wsc-app-sample
    app.kubernetes.io/version: "5.25.0"
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
