apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wproofreader.fullname" . }}
  labels:
    {{- include "wproofreader.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wproofreader.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print .Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wproofreader.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wproofreader.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: container-port
              containerPort: {{ include "wproofreader.containerPort" . }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /{{ .Values.virtualDir }}
              port: container-port
              scheme: {{ if .Values.useHTTPS }}HTTPS{{ else }}HTTP{{ end }}
            {{- with .Values.livenessProbeOptions }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: "/{{ .Values.virtualDir }}/api?cmd=status"
              port: container-port
              scheme: {{ if .Values.useHTTPS }}HTTPS{{ else }}HTTP{{ end }}
            {{- with .Values.readinessProbeOptions }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or (.Values.useHTTPS | and .Values.certFile) .Values.dictionaries.localPath .Values.dictionaries.existingClaim }}
          volumeMounts:
            {{- if .Values.useHTTPS | and .Values.certFile }}
            - mountPath: {{ .Values.certMountPath }}
              name: tls-secret-volume
            {{- end }}
            {{- if or .Values.dictionaries.localPath .Values.dictionaries.existingClaim }}
            - mountPath: {{ .Values.dictionaries.mountPath }}
              name: dictionaries-volume
            {{- end }}
          {{- end }}
          env:
            - name: PROTOCOL
              value: {{ if .Values.useHTTPS }}"1"{{ else }}"2"{{ end }}
            - name: WEB_PORT
              value: {{ .Values.webPort | default (include "wproofreader.defaultWebPort" .) | quote }}
            - name: VIRTUAL_DIR
              value: {{ .Values.virtualDir }}
            - name: LICENSE_TICKET_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "wproofreader.fullname" . }}-lic
                  key: license
      {{- if or (.Values.useHTTPS | and .Values.certFile) .Values.dictionaries.localPath .Values.dictionaries.existingClaim }}
      volumes:
        {{- if .Values.useHTTPS | and .Values.certFile }}
        - name: tls-secret-volume
          secret:
            secretName: {{ include "wproofreader.fullname" . }}-cert
        {{- end }}
        {{- if or .Values.dictionaries.localPath .Values.dictionaries.existingClaim }}
        - name: dictionaries-volume
          persistentVolumeClaim:
            claimName: {{ default (include "wproofreader.pvcName" .) .Values.dictionaries.existingClaim }}
        {{- end }}
      {{- end }}
      {{- if and .Values.dictionaries.enabled .Values.dictionaries.localPath }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.nodeAffinityLabel }}
                    operator: Exists
      {{- else if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
