apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wproofreader.fullname" . }}-lic
  labels:
    {{- include "wproofreader.labels" . | nindent 4 }}
type: Opaque
data:
  licence: {{ .Values.licenceTicketID | toString | b64enc | quote }}

---
{{- if .Values.useHTTPS | and .Values.certFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wproofreader.fullname" . }}-cert
  labels:
    {{- include "wproofreader.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "wproofreader.readCert" . | nindent 2 -}}
{{- end }}