apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "wproofreader.fullname" .) }}
  labels:
    {{- include "wproofreader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "wproofreader.servicePort" . }}
      targetPort: container-port
      protocol: TCP
  selector:
    {{- include "wproofreader.selectorLabels" . | nindent 4 }}
