{{- if .Values.dictionaries.localPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "wproofreader.fullname" . }}-dict
  labels:
    {{- include "wproofreader.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.dictionaries.storageClassName }}
  capacity:
    storage: {{ .Values.dictionaries.volumeSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: {{ .Values.dictionaries.localPath }}
  {{- .Values.affinity | toYaml | replace "requiredDuringSchedulingIgnoredDuringExecution" "required" | nindent 2 }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wproofreader.fullname" . }}-dict
  labels:
    {{- include "wproofreader.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.dictionaries.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.dictionaries.volumeSize }}
{{- end }}