{{- if .Values.dictionaries.enabled }}
{{- if not .Values.dictionaries.existingClaim }}
{{- if .Values.dictionaries.localPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "wproofreader.fullname" . }}-dict
  labels:
    {{- include "wproofreader.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.dictionaries.storageClassName | default "standard" }}
  capacity:
    storage: {{ .Values.dictionaries.volumeSize | default "20Gi" }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.dictionaries.accessMode | default "ReadWriteMany" }}
  local:
    path: {{ .Values.dictionaries.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: {{ .Values.nodeAffinityLabel }}
              operator: Exists
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wproofreader.pvcName" . }}
  labels:
    {{- include "wproofreader.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.dictionaries.storageClassName | default "standard" }}
  accessModes:
    - {{ .Values.dictionaries.accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .Values.dictionaries.volumeSize | default "20Gi" }}
{{- end }}
{{- end }}
