
useHTTPS: false
webPort: ""
licenseTicketID: ""
virtualDir: wscservice

# relative paths of key and cert file pairs within the Helm Chart directory
certFile: ""
keyFile: ""
certMountPath: "/certificate"

# custom dictionaries on the node
dictionaries:
  localPath: ""
  mountPath: "/dictionaries"
  volumeSize: 20Gi
  storageClassName: "standard"

replicaCount: 1

image:
  repository: webspellchecker/wproofreader
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: ""

resources: {}
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "app.wproofreader.com/instance"
              operator: Exists

# default deployment strategy for Kubernetes:
# allow no more than 25% (no fewer than 1) of pods be
# unavailable or allocated over max (surge) during update
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%