# License and database credentials from existing Secrets, with db-manager provisioning,
# as the WProofreader stack uses them.
licenseExistingSecret: wproofreader-license
database:
  enabled: true
  host: mysql-primary.wsc.svc.cluster.local
  existingSecret: wproofreader-db
databaseProvisioning:
  enabled: true
